name: havadurumu
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0
  csv: ^5.0.0
  google_sign_in: ^5.0.7
  intl: ^0.19.0
  permission_handler: ^11.0.0
  particles_flutter: ^1.0.0
  image_picker: ^0.8.5+3
  speech_to_text: ^7.0.0
  http: ^1.3.0
  rnd: ^0.2.0
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.2
  reactive_forms: ^17.0.1
  auto_size_text: ^3.0.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  geolocator: ^11.0.0
  flutter_cache_manager: ^3.4.1
  flutter_tts: ^4.2.0
  location: ^7.0.1
  weatherapi:
    path: lib/local_packages/weatherapi
  flutter_signin_button: ^2.0.0
  connectivity_plus: ^6.1.2
  firebase_messaging: ^15.2.2
  flutter_local_notifications: 18.0.1
  get_storage: 2.1.1
  multi_select_flutter: ^4.1.3
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
    - assets/csv/
    - assets/json/